// irig106-tmats/build.rs
//
// # Build Script — Attribute Registry Code Generation
//
// Reads `data/attributes.toml` and generates `src/version_generated.rs`
// containing a static array of AttrMeta entries, eliminating the need to
// manually synchronize the TOML source-of-truth with the Rust code.
//
// ## Traceability:
//   L3-VERSION-006: Build-time registry generation from declarative source
//   L3-VERSION-007: Source-of-truth file derived from §9.5 tables

use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=data/attributes.toml");

    let toml_path = Path::new("data/attributes.toml");
    if !toml_path.exists() {
        // If TOML not present, skip codegen (use hand-written fallback)
        return;
    }

    let toml_content = fs::read_to_string(toml_path).expect("failed to read data/attributes.toml");

    let entries = parse_toml_attributes(&toml_content);

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("version_generated.rs");

    let mut out = fs::File::create(&out_path).expect("failed to create version_generated.rs");

    write_generated_code(&mut out, &entries).expect("failed to write generated code");
}

// ─── Simple TOML parser (no external dependency) ─────────────────────────────
//
// Parses the subset of TOML used by attributes.toml:
//   [[attributes]]
//   key = "value"
//   key = integer
//
// This avoids requiring the `toml` crate as a build dependency.

#[derive(Debug, Default)]
struct AttrEntry {
    code_name: String,
    display_name: String,
    group: String,
    section: String,
    introduced: String,
    deprecated: Option<String>,
    removed: Option<String>,
    required: String,
    mfs: Option<u16>,
    value_type: String,
    keywords: Vec<String>,
    description: String,
}

fn parse_toml_attributes(content: &str) -> Vec<AttrEntry> {
    let mut entries = Vec::new();
    let mut current: Option<AttrEntry> = None;

    for line in content.lines() {
        let line = line.trim();

        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        if line == "[[attributes]]" {
            if let Some(entry) = current.take() {
                entries.push(entry);
            }
            current = Some(AttrEntry::default());
            continue;
        }

        if let Some(ref mut entry) = current {
            if let Some((key, value)) = parse_kv(line) {
                match key {
                    "code_name" => entry.code_name = value,
                    "display_name" => entry.display_name = value,
                    "group" => entry.group = value,
                    "section" => entry.section = value,
                    "introduced" => entry.introduced = value,
                    "deprecated" => entry.deprecated = Some(value),
                    "removed" => entry.removed = Some(value),
                    "required" => entry.required = value,
                    "mfs" => entry.mfs = value.parse().ok(),
                    "value_type" => entry.value_type = value,
                    "keywords" => {
                        entry.keywords = value
                            .split(',')
                            .map(|s| s.trim().to_string())
                            .filter(|s| !s.is_empty())
                            .collect();
                    }
                    "description" => entry.description = value,
                    _ => {}
                }
            }
        }
    }

    if let Some(entry) = current {
        entries.push(entry);
    }

    entries
}

fn parse_kv(line: &str) -> Option<(&str, String)> {
    let eq_pos = line.find('=')?;
    let key = line[..eq_pos].trim();
    let raw_value = line[eq_pos + 1..].trim();

    // Strip quotes if present
    let value = if raw_value.starts_with('"') && raw_value.ends_with('"') {
        raw_value[1..raw_value.len() - 1].to_string()
    } else {
        raw_value.to_string()
    };

    Some((key, value))
}

// ─── Code generation ─────────────────────────────────────────────────────────

fn write_generated_code(out: &mut fs::File, entries: &[AttrEntry]) -> std::io::Result<()> {
    writeln!(
        out,
        "// AUTO-GENERATED by build.rs from data/attributes.toml"
    )?;
    writeln!(out, "// DO NOT EDIT — modify data/attributes.toml instead")?;
    writeln!(out, "//")?;
    writeln!(out, "// Generated: {} entries", entries.len())?;
    writeln!(out)?;
    writeln!(
        out,
        "use crate::types_bridge::{{GroupPrefix, Irig106Version}};"
    )?;
    writeln!(
        out,
        "use crate::version::{{AttrMeta, RequiredTag, ValueType}};"
    )?;
    writeln!(out)?;
    writeln!(
        out,
        "pub(crate) static GENERATED_REGISTRY: &[AttrMeta] = &["
    )?;

    for entry in entries {
        let group = match entry.group.as_str() {
            "G" => "GroupPrefix::G",
            "T" => "GroupPrefix::T",
            "R" => "GroupPrefix::R",
            "M" => "GroupPrefix::M",
            "P" => "GroupPrefix::P",
            "D" => "GroupPrefix::D",
            "B" => "GroupPrefix::B",
            "S" => "GroupPrefix::S",
            "C" => "GroupPrefix::C",
            _ => "GroupPrefix::Unknown('?')",
        };

        let introduced = version_variant(&entry.introduced);
        let deprecated = match &entry.deprecated {
            Some(v) => format!("Some({})", version_variant(v)),
            None => "None".to_string(),
        };
        let removed = match &entry.removed {
            Some(v) => format!("Some({})", version_variant(v)),
            None => "None".to_string(),
        };

        let required = match entry.required.as_str() {
            "R" => "RequiredTag::Required",
            "RO" => "RequiredTag::RequiredOptional",
            "R_CH10" => "RequiredTag::RequiredCh10",
            "RO_CH10" => "RequiredTag::RequiredOptionalCh10",
            "RO_PAK" => "RequiredTag::RequiredPak",
            _ => "RequiredTag::Optional",
        };

        let mfs = match entry.mfs {
            Some(v) => format!("Some({v})"),
            None => "None".to_string(),
        };

        let value_type = match entry.value_type.as_str() {
            "Keyword" => "ValueType::Keyword",
            "Text" => "ValueType::Text",
            "Integer" => "ValueType::Integer",
            "Decimal" => "ValueType::Decimal",
            "Scientific" => "ValueType::Scientific",
            "Date" => "ValueType::Date",
            "Boolean" => "ValueType::Boolean",
            _ => "ValueType::FreeForm",
        };

        let keywords = if entry.keywords.is_empty() {
            "&[]".to_string()
        } else {
            let items: Vec<String> = entry
                .keywords
                .iter()
                .map(|k| format!("\"{}\"", k))
                .collect();
            format!("&[{}]", items.join(", "))
        };

        writeln!(out, "    AttrMeta {{")?;
        writeln!(
            out,
            "        code_name_pattern: \"{}\",",
            escape_backslash(&entry.code_name)
        )?;
        writeln!(out, "        display_name: \"{}\",", entry.display_name)?;
        writeln!(out, "        group: {},", group)?;
        writeln!(out, "        spec_section: \"{}\",", entry.section)?;
        writeln!(out, "        introduced_in: {},", introduced)?;
        writeln!(out, "        deprecated_in: {},", deprecated)?;
        writeln!(out, "        removed_in: {},", removed)?;
        writeln!(out, "        required_tag: {},", required)?;
        writeln!(out, "        max_field_size: {},", mfs)?;
        writeln!(out, "        value_type: {},", value_type)?;
        writeln!(out, "        keywords: {},", keywords)?;
        writeln!(out, "        description: \"{}\",", entry.description)?;
        writeln!(out, "    }},")?;
    }

    writeln!(out, "];")?;

    Ok(())
}

fn version_variant(ver_str: &str) -> String {
    match ver_str.trim() {
        "04" => "Irig106Version::V106_04".to_string(),
        "05" => "Irig106Version::V106_05".to_string(),
        "07" => "Irig106Version::V106_07".to_string(),
        "09" => "Irig106Version::V106_09".to_string(),
        "11" => "Irig106Version::V106_11".to_string(),
        "13" => "Irig106Version::V106_13".to_string(),
        "15" => "Irig106Version::V106_15".to_string(),
        "17" => "Irig106Version::V106_17".to_string(),
        other => panic!("unknown IRIG 106 version: {other}"),
    }
}

fn escape_backslash(s: &str) -> String {
    s.replace('\\', "\\\\")
}
